method: random

metric:
  name: F1Score
  goal: maximize

parameters:

  experiment:
    parameters:
      model: 
        value: best
      dataset: 
        value: churn
      n_epochs:
        value: 100

  encoder:
    parameters:
      hidden_size:
        values: [32, 64, 96]
      mcc_out:
        values: [12, 14, 16]
      # rnn_units:
      #   values: [64, 96, 128, 160, 192]

  cnn:
    parameters:
      kernel_size:
        values: [4, 8, 12]
