method: random

metric:
  name: F1Score
  goal: maximize

parameters:

  experiment:
    parameters:
      model: 
        value: lstm
      dataset: 
        value: churn
      n_epochs:
        value: 100

  encoder:
    parameters:
      hidden_size:
        values: [4, 8, 16]
      mcc_out:
        values: [4, 8, 16] 

  rnn:
    parameters:
      hidden_size:
        values: [4, 6, 8, 10, 12, 16]
      bidirectional:
        value: [False, True]
          