method: random

metric:
  name: F1Score
  goal: maximize

parameters:

  experiment:
    parameters:
      model: 
        value: best
      dataset: 
        value: raif
      n_epochs:
        value: 100

  encoder:
    parameters:
      hidden_size:
        values: [64, 96]
      mcc_out:
        values: [4, 8, 10, 12, 14, 16]
      # rnn_units:
      #   values: [128, 160, 192, 256]

  cnn:
    parameters:
      kernel_size:
        values: [4, 8, 12]