test_size: 0.8

trainer_args:
  max_epochs: 500

train_dl_args:
  batch_size: 196
  num_workers: 4

val_dl_args:
  batch_size: 8
  num_workers: 4

dataset:
  min_len: 20
  random_min_seq_len: 20
  random_max_seq_len: 60

defaults:
 - encoder: rnn_reduced
 - decoder: lstmcell
 - module_ae: vanilla_pretrained
