early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_loss

trainer_args:
  max_epochs: 100
  precision: 16
  enable_checkpointing: false

datamodule_args:
  train_batch_size: 256
  train_num_workers: 4
  valid_batch_size: 256
  valid_num_workers: 4

defaults:
 - encoder: rnn_reduced
 - decoder: lstmcell
 - module_ae: vanilla_pretrained
