# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: val_loss
#   mode: min
#   divergence_threshold: 10
checkpoint_metric: val_loss
trainer_args:
  max_epochs: 0
  precision: 16

datamodule_args:
  train_batch_size: 256
  train_num_workers: 4
  valid_batch_size: 256
  valid_num_workers: 4

defaults:
 - encoder: rnn_reduced
 - decoder: lstmcell
 - module_ae: vanilla/frozen
