# early_stopping:
#   _target_: pytorch_lightning.callbacks.EarlyStopping
#   monitor: val_loss
#   mode: min
#   divergence_threshold: 10
checkpoint_metric: val_loss
save_path: saved_models/encoders/ae_nlp_churn.pth

datamodule_args:
  train_batch_size: 1024
  train_num_workers: 4
  valid_batch_size: 1024
  valid_num_workers: 4

defaults:
 - encoder: ae_nlp_rnn
 - decoder: lstmcell
 - module: vanilla/from_scratch
