checkpoint_metric: val_loss
save_path: saved_models/encoders/transformer_churn.pth
trainer_args:
  max_steps: 8000
  precision: 16

datamodule_args:
  train_batch_size: 1024
  train_num_workers: 4
  valid_batch_size: 1024
  valid_num_workers: 4

defaults:
 - encoder: transformer
 - module: transformer
