name: coles_emb_churn

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 64
  valid_batch_size: 64
  train_num_workers: 4
  valid_num_workers: 4

model:
  _target_: src.coles.CustomCoLES
  optimizer_partial:
    _partial_: True
    _target_: torch.optim.Adam
    lr: .001
    weight_decay: .00005
  lr_scheduler_partial:
    _partial_: True
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    factor: .5
    patience: 2
  sequence_encoder:
    _target_: ptls.nn.RnnSeqEncoder
    trx_encoder:
      _target_: src.nn.PretrainedRnnSeqEncoder
      path_to_dict: saved_models/encoders/encoder_dict.pth
      trx_encoder:
        _target_: ptls.nn.TrxEncoder
        use_batch_norm_with_lens: True
        norm_embeddings: False
        embeddings_noise: 0.0003
        embeddings: {mcc_code: {in: 345, out: 24}}
        numeric_values: {amount: identity}
      hidden_size: 1024
      bidir: False
      trainable_starter: static
      type: lstm
      is_reduce_sequence: False
    hidden_size: 1024
    type: lstm

defaults:
  - trainer_coles: trainer 