_target_: src.datasets.CustomColesDatasetWithSplitter
split_count: 1
min_len: 15
col_time: event_time
splitter:
  _target_: src.datasets.splitters.TimeCLSampler
  min_len: ${..min_len}
  max_len: 150
  split_count: ${..split_count}
  llambda: 0.4
  rlambda: 0.6
