enable_early_stopping: false

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  min_delta: .01
  patience: 5
  verbose: True

checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  log_every_n_steps: 10
  callbacks: callbacks
  devices: 1
  max_steps: 8000
  precision: 16
  # pass FAST_DEV_RUN env variable to trainer, if set
  fast_dev_run: ${oc.decode:${oc.env:FAST_DEV_RUN,null}}
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: macro_micro_coles
    tags: [transformer]
