_target_: src.generation.modules.VanillaAE
loss_weights:
  mcc: 5
  amount: 1

mcc_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 100]

amount_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 1]

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005
scheduler: 
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 50
  min_lr: 0.0001
scheduler_config:
  monitor: val_loss
