_target_: src.generation.modules.VanillaAE
loss_weights:
  mcc: 5
  amount: 1

encoder_weights: coles_best_state_dict.pth

mcc_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 100]

amount_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 1]

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005
scheduler: 
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 250
  gamma: 0.5
