_target_: src.nn.AttnNHPSeqEncoder
trx_encoder: null # no trx encoder for AttnNHP
is_reduce_sequence: False
input_size: 32 # hidden_size // 2
hidden_size: 64
use_ln: False
time_emb_size: 4
num_layers: 2
num_heads: 2
dropout: 0.
num_types: 100
num_event_types_pad: 101
pad_token_id: 100
reducer: maxpool