_target_: ptls.nn.RnnSeqEncoder
trx_encoder:
  _target_: ptls.nn.TrxEncoder
  embeddings_noise: .005
  embeddings: {mcc_code: {in: 202, out: 32}}
  numeric_values: {event_time: log}
hidden_size: 800 
type: gru
is_reduce_sequence: True
