_target_: ptls.nn.RnnSeqEncoder
trx_encoder:
  _target_: src.nn.PretrainedRnnSeqEncoder
  path_to_dict: saved_models/encoders/encoder_dict.pth
  trx_encoder:
    _target_: ptls.nn.TrxEncoder
    use_batch_norm_with_lens: True
    norm_embeddings: False
    embeddings_noise: 0.0003
    embeddings: {mcc_code: {in: 344, out: 24}}
    numeric_values: {amount: identity}
  hidden_size: 1024
  bidir: False
  trainable_starter: static
  type: lstm
  is_reduce_sequence: False
hidden_size: 1024
type: lstm
