defaults:
 - preprocessing: churn
 - dataset: coles
 - encoder: coles_churn
 - module: coles_churn
 - trainer: coles
 - validation: [event_type, event_time, local_target, global_target]
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 128
  valid_batch_size: 128
  train_num_workers: 8
  valid_num_workers: 8
