defaults:
  - preprocessing: churn # change to * for other datasets
  - backbone: coles # change config/backbone/coles.yaml for other datasets
  - validation: local_target
  - _self_

pretrain: false

