defaults:
  - preprocessing: churn_100
  - dataset: basic
  - encoder: transformer
  - module: transformer
  - trainer: transformer
  - validation: event_type_100
  - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 1024
  train_num_workers: 4
  valid_batch_size: 1024
  valid_num_workers: 4
