name: global_target

sequence_encoder:
  _target_: ptls.nn.RnnSeqEncoder
  trx_encoder:
    _target_: ptls.nn.TrxEncoder
    use_batch_norm_with_lens: True
    norm_embeddings: False
    embeddings_noise: 0.0003
    embeddings: {mcc_code: {in: 345, out: 24}}
    numeric_values: {amount: identity}
  hidden_size: 1024
  bidir: False
  trainable_starter: static
  type: lstm

path_to_state_dict: saved_models/coles_churn.pth

embed_data:
  batch_size: 64
  device: cuda

n_runs: 10

model:
  _target_: lightgbm.LGBMClassifier
  n_estimators: 500
  boosting_type: gbdt
  subsample: 0.5
  subsample_freq: 1
  learning_rate: 0.02
  feature_fraction: 0.75
  max_depth: 6
  lambda_l1: 1
  lambda_l2: 1
  min_data_in_leaf: 50
  random_state: 42
  n_jobs: 8
  verbose: -1
