_target_: src.modules.VanillaAE
num_types: 100
loss_weights:
  mcc: 5
  amount: 1

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005
scheduler: 
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 800
  gamma: 0.5
