checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: logs/checkpoints/coles
  filename: coles_model

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  min_delta: .01
  patience: 5
  verbose: True

logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: logs/tensorboard

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  max_epochs: 50
  log_every_n_steps: 20