method: random

metric:
  name: F1Score
  goal: maximize

parameters:

  experiment:
    parameters:
      model: 
        value: best
      dataset: 
        value: churn
      n_epochs:
        value: 100

  encoder:
    parameters:
      dict_size:
        value: 344
      hidden_size:
        value: 64
      mcc_out:
        value: 16
      rnn_units:
        value: 160

  # cnn:
  #   parameters:
  #     kernel_size:
  #       values: [4, 8, 12]
