defaults:
 - dataset: basic
 - encoder: rnn_encoder_churn # change to 'rnn_encoder_*' for other datasets
 - decoder: lstmcell
 - module: autoencoder
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 1024
  train_num_workers: 4
  valid_batch_size: 1024
  valid_num_workers: 4

trainer:
  max_steps: 2000
