defaults:
 - dataset: basic
 - encoder: rnn_encoder_churn # change to 'rnn_encoder_*' for other datasets
 - module: ar
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 128
  train_num_workers: 8
  valid_batch_size: 128
  valid_num_workers: 8

trainer:
  max_epochs: 60
