defaults:
 - dataset: coles
 - encoder: rnn_encoder_churn # change to 'rnn_encoder_*' for other datasets
 - module: coles_churn # change to 'coles_*' for other datasets
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 128
  valid_batch_size: 128
  train_num_workers: 8
  valid_num_workers: 8

trainer:
  max_epochs: 60
  log_every_n_steps: 10
