defaults:
 - dataset: cotic
 - encoder: cotic_churn
 - module: cotic_churn
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 20
  valid_batch_size: 20
  test_batch_size: 20
  train_num_workers: 2
  valid_num_workers: 2
  test_num_workers: 2

trainer:
  max_epochs: 100
  accumulate_grad_batches: 1
  gradient_clip_val: 1
  accelerator: gpu
  devices: 1
