defaults:
 - dataset: basic
 - encoder: gpt
 - module: gpt_contrastive
 - _self_

datamodule:
  _target_: ptls.frames.PtlsDataModule
  train_batch_size: 128
  train_num_workers: 8
  valid_batch_size: 128
  valid_num_workers: 8

trainer:
  max_epochs: 60
