name: age

dir_path: data/preprocessed_new
train_file_name: ${.name}.parquet

ignore_existing_preproc: False

coles:
  pandas_preprocessor:
    dir_path: preproc_data/${dataset.name}
    name: pandas_preprocessor.p
  valid_size: .1
  test_size: .1
  random_state: 42