name: churn

dir_path: data/preprocessed_new
train_file_name: ${.name}.parquet

ignore_existing_preproc: False

coles:
  pandas_preprocessor:
    dir_path: preproc_data/${dataset.name}
    name: pandas_preprocessor.p
  test_size: .2