_target_: src.generation.modules.MLMModule
loss_weights:
  mcc: 5
  amount: 1

mcc_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 100]

amount_head:
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 1]

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0005
scheduler: 
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 0.001
  total_steps: 8000
