_target_: src.generation.modules.VanillaAE
_partial_: True
loss_weights:
  mcc: 1
  amount: 1
mcc_vocab_size: 344

optimizer_config: 
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.01
  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CyclicLR
    mode: triangular2
    base_lr: 0.0001
    cycle_momentum: false
    max_lr: 0.003
    step_size_up: 50