_target_: src.generation.modules.VanillaAE
loss_weights:
  mcc: 5
  amount: 1

encoder_weights: coles_best_state_dict.pth
unfreeze_enc_after: -1

mcc_head_factory:
  _partial_: true
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 100]

amount_head_factory:
  _partial_: true
  _target_: torchvision.ops.MLP
  hidden_channels: [4096, 1]

optimizer_factory:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 0.001
scheduler_factory: 
  _partial_: true
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 10
  min_lr: 0.0001
scheduler_config:
  monitor: val_loss
