_target_: src.generation.modules.VanillaAE
_partial_: True
loss_weights:
  mcc: 5
  amount: 1
encoder_weights: coles_best_state_dict.pth
mcc_vocab_size: 344

optimizer_config: 
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.002
