method: random

metric:
  name: F1Score
  goal: maximize

parameters:

  experiment:
    parameters:
      model: 
        value: gru
      dataset: 
        value: default
      n_epochs:
        value: 100

  encoder:
    parameters:
      hidden_size:
        values: 16
      mcc_out:
        values: 16

  rnn:
    parameters:
      hidden_size:
        values: 12
      bidirectional:
        values: 0