_target_: pytorch_lightning.loggers.CometLogger
save_dir: logs/coles
project_name: macro-micro-coles
experiment_name: COLES
display_summary_level: 0
# Note: pass API key through comet.config or env var COMET_API_KEY
