_target_: pytorch_lightning.loggers.CometLogger
save_dir: logs/coltic
api_key: agnHNC2vEt7tOxnnxT4LzYf7Y
project_name: macro-micro-coles
workspace: stalex2902
experiment_name: COTIC
display_summary_level: 0
